name: ci

on:
  push:

env:
  UBUNTU_DOC_TEST_TAG: shanakaprgeeth/ubuntu-dpdk:test
  UBUNTU_DOC_LATEST_TAG: shanakaprgeeth/ubuntu-dpdk:latest
  RHEL_DOC_TEST_TAG: shanakaprgeeth/ubuntu-dpdk:test
  RHEL_DOC_LATEST_TAG: shanakaprgeeth/ubuntu-dpdk:latest

jobs:
  ubuntu-dpdk:
    runs-on: ubuntu-latest
    steps:
      #- name: Login to Docker Hub
      #  uses: docker/login-action@v3
      #  with:
      #    username: ${{ vars.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: ls -la
      - run: find . -name Dockerfile
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          load: true
          context: .
          file: ./docker-ubuntu-dpdk/Dockerfile
          tags: ${{ env.UBUNTU_DOC_TEST_TAG }}
      - 
        name: Test
        run: |
          docker run --rm ${{ env.UBUNTU_DOC_TEST_TAG }}

      - 
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: false
          context: .
          file: ./docker-ubuntu-dpdk/Dockerfile
          tags: ${{ env.UBUNTU_DOC_LATEST_TAG }}
  rhel-dpdk:
    runs-on: ubuntu-latest
    steps:
      #- name: Login to Docker Hub
      #  uses: docker/login-action@v3
      #  with:
      #    username: ${{ vars.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          load: true
          context: .
          file: ./docker-rhel-dpdk/Dockerfile
          tags: ${{ env.RHEL_DOC_TEST_TAG }}
      - 
        name: Test
        run: |
          docker run --rm ${{ env.RHEL_DOC_TEST_TAG }}

      - 
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: false
          context: .
          file: ./docker-rhel-dpdk/Dockerfile
          tags: ${{ env.RHEL_DOC_LATEST_TAG }}