name: ci

on:
  push:

env:
  UBUNTU_DOC_TEST_TAG: shanakaprageeth/ubuntu24-dpdk:test
  UBUNTU_DOC_LATEST_TAG: shanakaprageeth/ubuntu24-dpdk:latest
  RHEL_DOC_TEST_TAG: shanakaprageeth/rhel8-dpdk:test
  RHEL_DOC_LATEST_TAG: shanakaprageeth/rhel8-dpdk:latest

jobs:
  ubuntu-dpdk:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        if: github.ref_name == 'master' || github.ref_name == 'main'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build Ubuntu-dpdk Test Image
        uses: docker/build-push-action@v6
        with:
          load: true
          context: ./docker-ubuntu-dpdk/
          file: ./docker-ubuntu-dpdk/Dockerfile
          tags: ${{ env.UBUNTU_DOC_TEST_TAG }}
      - 
        name: Test Ubuntu Container
        run: |
          .sudo /ci_tests.sh ${{ env.UBUNTU_DOC_TEST_TAG }}
      - 
        name: Retag and Push Ubuntu-dpdk Image
        if: github.ref_name == 'master' || github.ref_name == 'main'
        run: |
          docker tag ${{ env.UBUNTU_DOC_TEST_TAG }} ${{ env.UBUNTU_DOC_LATEST_TAG }}
          docker push ${{ env.UBUNTU_DOC_LATEST_TAG }}
  rhel-dpdk:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        if: github.ref_name == 'master' || github.ref_name == 'main'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build RHEL Test Image
        uses: docker/build-push-action@v6
        with:
          load: true
          context: ./docker-rhel-dpdk/
          file: ./docker-rhel-dpdk/Dockerfile
          tags: ${{ env.RHEL_DOC_TEST_TAG }}
      - 
        name: Test RHEL Container
        run: |
          sudo ./ci_tests.sh ${{ env.RHEL_DOC_TEST_TAG }}
      - 
        name: Retag and Push RHEL Image
        if: github.ref_name == 'master' || github.ref_name == 'main'
        run: |
          docker tag ${{ env.RHEL_DOC_TEST_TAG }} ${{ env.RHEL_DOC_LATEST_TAG }}
          docker push ${{ env.RHEL_DOC_LATEST_TAG }}
